name: abutil
description: Common Flutter utilities for platform detection, app subtree restart, and update checks.
version: 1.2.2
homepage: https://github.com/abandoft/abutil
repository: https://github.com/abandoft/abutil
issue_tracker: https://github.com/abandoft/abutil/issues

topics:
  - flutter
  - platform
  - utilities

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
